services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    restart: always
    ports:
      - '${API_PORT}:${API_PORT}'
    environment:
      API_PORT: ${API_PORT}
      API_DATABASE_HOST: ${API_DATABASE_HOST}
      API_DATABASE_PORT: ${API_DATABASE_PORT}
      API_DATABASE_NAME: ${API_DATABASE_NAME}
      API_DATABASE_USER: ${API_DATABASE_USER}
      API_DATABASE_PASSWORD: ${API_DATABASE_PASSWORD}
      API_WEBAPP_URL: ${API_WEBAPP_URL}
    networks:
      - app_network

  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - '${VITE_PORT}:${VITE_PORT}'
    environment:
      VITE_PORT: ${VITE_PORT}
      VITE_API_URL: ${VITE_API_URL}
    networks:
      - app_network

networks:
  app_network:
